#!/bin/bash

pwd=$PWD
cd /home/dani/SelfHome/

sleep 10
nice -n -20 Core/./server 4001 Core/devices /dev/ttyACM0 > /home/dani/SelfHome/Core/log &

cd Middle
sleep 10
(su -c "/usr/bin/java -jar Middle.jar -c settings/middle_conf" dani > /home/dani/SelfHome/Middle/log &)

#cd ../Flooding
#sleep 10
#(su dani ; /usr/bin/python flooding.py localhost 4000 > /home/dani/SelfHome/Flooding/log &)

cd ../SelfHomeBot
#nodejs TelegramBot.js

cd $pwd